# Generated by Django 2.2.3 on 2019-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('store_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.IntegerField(default=4)),
                ('phone_no', models.IntegerField(default=11)),
                ('tin_no', models.IntegerField(default=19)),
                ('birth_of_date', models.DateTimeField()),
                ('optional_website', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
            ],
        ),
    ]
